version: '3.8'

services:

  ##########################
  ###### Kong Service ######
  ##########################

  kong:
    build: 
      context: ./kongService
      dockerfile: Dockerfile
    hostname: kong
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    volumes:
      - ./kongService/kong.yml:/etc/kong/kong.yml
    networks:
      - kong_network
    restart: unless-stopped

  ##########################
  # Notification Service ###
  ##########################

  watchlist:
    build: 
      context: ./notificationService/watchlist
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    networks:
      - notification_service
      - kong_network
    environment:
      - DB_URL=watchlist_db:27017
    restart: unless-stopped
  
  notification_manager:
    build: 
      context: ./notificationService/manage_notifications
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3001:3001
    networks:
      - notification_service
      - queue_network
    environment:
      - AMQP_SERVER=amqp://rabbitmq:5672
      - WATCHLIST_URL=http://watchlist:3000/
      - TELEBOT_URL=http://telebot:3002/
    restart: unless-stopped

  telebot:
    build: 
      context: ./notificationService/telebot_esd
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3002:3002
    networks:
      - notification_service
    environment:
      - AMQP_SERVER=amqp://rabbitmq:5672
      - BOT_TOKEN=7039505633:AAFoCvJc3XwP8N7bUd1XsjkCP5rH311TrWQ
      - BOT_URL=https://api.telegram.org/bot
    restart: unless-stopped

  watchlist_db:
    build:
      context: ./notificationService
      dockerfile: watchlistDBDockerfile
    hostname: watchlist_db
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_DATABASE=watchlist
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - watchlist_db:/data/db
    networks:
      - notification_service
    restart: unless-stopped


  ##########################
  ###### rabbit MQ    ######
  ##########################

  rabbitmq:
    build:
      context: ./rabbitMQ
      dockerfile: Dockerfile
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - queue_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      # - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    restart: unless-stopped
  

  ##########################
  #### sentiment Service ###
  ##########################


  sentiment_app:
    build: 
      context: ./sentimentService/sentiment_express
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "5001:5001"
    networks:
      - sentiment_network
      - queue_network
      - kong_network
    environment:
      - SENTIMENT_SERVICE_URL=http://sentiment_service:5002/
      - DB_URL=sentiment_db:27017
      - AMQP_SERVER=amqp://rabbitmq:5672
      - SCRAPER_URL=http://scraper:5000
    depends_on:
      - sentiment_db
      - sentiment_service
      # - rabbitmq
    restart: unless-stopped

  sentiment_service:
    build: 
      context: ./sentimentService/sentiment_service
      dockerfile: Dockerfile
    command: gunicorn -w 1 --threads 2 -b :5002 --timeout 600 sentimentApp:app
    hostname: sentiment_service
    ports:
      - "5002:5002"
    networks:
      - sentiment_network
    restart: unless-stopped

  scraper:
    build:
      context: ./sentimentService/scraper
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: ["node", "app.js"]
    environment:
      - ALPHA_VANTAGE_API_KEY=youralphavantageapikey
      - PORT=5000
      - DB_URL=scraper_db:27017
    restart: unless-stopped
    networks:
      - sentiment_network
      - scraper_network

  sentiment_db:
    build:
      context: ./sentimentService
      dockerfile: sentimentDBDockerfile
    hostname: sentiment_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=sentiments
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - sentiment_db:/data/db
    networks:
      - sentiment_network
    restart: unless-stopped

  scraper_db:
    build:
      context: ./sentimentService
      dockerfile: scraperDBDockerfile
    hostname: scraper_db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=scraper
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - scraper_db:/data/db
    networks:
      - scraper_network
    restart: unless-stopped


  ##########################
  #### USER Service   ######
  ##########################

  user_service:
    build: 
      context: ./userServices/User
      dockerfile: Dockerfile
    command: gunicorn -w 1 --threads 2 -b :5000 --timeout 600 User:app
    hostname: user_service
    ports:
      - "6000:6000"
    environment:
      - SQL_URI=postgresql://postgres:root@user_db:5432
    networks:
      - user_network
      - kong_network
    restart: unless-stopped

  user_db:
    build: 
      context: ./userServices
      dockerfile: userDBDockerfile
    hostname: user_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: user_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - user_network
    restart: unless-stopped

  comments_service:
    build: 
      context: ./userServices/comments
      dockerfile: Dockerfile  
    command: npm start
    ports:
      - "6001:6001"
    networks:
      - comments_netowork
      - kong_network
      - queue_network
    environment:
      - MONGO_URI=comments_db:27017
      - AMQP_SERVER=amqp://rabbitmq:5672
    restart: unless-stopped
    
  comments_db:
    build: 
      context: ./userServices
      dockerfile: commentsDBDockerfile
    hostname: comments_db
    ports:  
      - "27020:27017"
    environment:
      - MONGO_INITDB_DATABASE=comments
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - comments_db:/data/db
    networks:
      - comments_netowork
    restart: unless-stopped

volumes:
  watchlist_db:
  rabbitmq_data:
  sentiment_db:
  scraper_db:
  user_db_data:
  comments_db:

networks:
  kong_network:
    driver: bridge
    name: kong_network
  queue_network:
    driver: bridge
    name: queue_network
  notification_service:
    driver: bridge
    name: watchlist
  sentiment_network:
    driver: bridge
    name: sentiment_network
  scraper_network:  
    driver: bridge
    name: scraper_network
  user_network: 
    driver: bridge
    name: user_network
  comments_netowork:
    driver: bridge
    name: comments_network