version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443" # Expose port 443 for https
    volumes:
      - .:/usr/src/app
    command: ["nginx", "-g", "daemon off;"]
    # networks:
    #   - kong_network
    environment:
      # - KONG_URL=/kong/
      - KONG_URL=/kong/