name: "Terraform Destroy"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init iac

      - name: Terraform Destroy
        run: terraform destroy -auto-approve iac
