name: "Terraform Destroy"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gCloud
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2.1.0'
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./iac
        env:
          TF_VAR_gcp_sa_key: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve 
        working-directory: ./iac
        env:
          TF_VAR_gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      
      - name: delete disks
        run: |
          while IFS= read -r disk
          do
            name=$(echo $disk | awk '{print $1}')
            zone=$(echo $disk | awk '{print $2}')

            echo $name
            echo $zone

            gcloud compute disks delete $curr_disk_name --zone=$curr_disk_zone --quiet

          done < <(gcloud compute disks list --format="value(name,LOCATION)")
        


